### ISSUE TITLE
Huuge security issues

### ISSUE THREAD

**Issue by Serhx4** [divizia/db-constructor#11]
**Sometimes I feel myself like a hacker :)**
Looks like we shouldn't show BCrypted password for users:
![wrong password](https://img001.prntscr.com/file/img001/WYxDfnK_Q2qcbDsh-dzy4g.png)

Just for security purposes..
![show password](https://img001.prntscr.com/file/img001/fnUEbapjShuNKyFWjAVYhQ.png)

**Comment by inrosh** [comment]
the user role also has such a problem
