### ISSUE TITLE
LocalDate displaying in Excel tables

### ISSUE THREAD

**Issue by Serhx4** [divizia/db-constructor#7]
**Hi there!**
@divizia, please take a look at this:
![Excel Date](https://img001.prntscr.com/file/img001/-Szno07lQ-iBppXW7d_UUw.png)
`B` column represents LocalDateTime from the table. Same for `E` column (Microsoft Office 2010).

Looks like [ExcelSaver](https://github.com/divizia/db-constructor/blob/master/src/main/java/com/divizia/dbconstructor/excel/ExcelSaver.java) should be updated to reach synergy with Excel date formats.

**Comment by lipiridi** [comment]
Honestly, it is correct excel date format. Excel gives us the opportunity to change view (to normal) of thoose cells in menu "format" (you can also set custom formatter).
But you are right, I didn't implement cells formating in ExcelSaver, so you can do that :)
